# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: qqread

on:
  workflow_dispatch:
  schedule:
    - cron: '*/11 * * * *'
  repository_dispatch:
    types: qqread
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone -b master https://github.com/kokilu/Actions.git ~/Actions
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: '运行 【qqread】'
        run: | 
          cd ~/Actions
          npm install 
          node jd_bean_change.js
        env:
            QQREAD_BODY: ${{ secrets.QQREAD_BODY }}
            QQREAD_TIMEURL: ${{ secrets.QQREAD_TIMEURL }}
            QQREAD_TIMEHD: ${{ secrets.QQREAD_TIMEHD }}
            QQREAD_CASH: ${{ secrets.QQREAD_CASH }}
