name: 中青阅读1

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
   - cron: '0 1-15/2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: 运行 【京豆变动通知】
        run: |
          node Task/Youth_AutoRead.js
